# -*- coding: utf-8 -*-
"""Basics of Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-hSKlbhC5XfjNOfUXGWRK8b1Ww3wXY6p

**Hello World Program**
"""

print('hello World')

"""**Numeric Data Types**"""

print('Python has 3 numeric datatypes: Integer, Float and Complex]')

v1 = 2
print(v1,'is of the data type',type(v1),'\n')

v2 = 3.14
print(v2,'is of the data type',type(v2),'\n')

v3 = 1j
print(v3,'is of the data type',type(v3),'\n')

v4 = True
print(v4,'is of the data type',type(v4),'\n')

"""**String DataType**"""

v5 = 'This is a string'
print(v5,'\n')
print('and It is of the data type',type(v5),'\n')

n = input('Enter your name: ')
c = input('Enter your favourite colour: ')
p = input('Enter a pet you would like to have: ')

print('your name is ' + n + ' and your favourite colour is ' + c + ' and you like to have ' + p + ' as a pet.')

name='Vinayak'
subject='aws'
dream='to live peacefully within yourself'
print('This program is created by {}, currently he is studying {} and one day he would like to {}.'.format(name,subject,dream))

L1 = ['Python','Linux','Networking','Git','SQL',1,2,55,1.234,True ]
print(type(L1))
print(L1[0])
L1[4] == 'Jenkins'
print(L1[4])

"""**List , Tuple, Dictionary and Working with them**"""

t1 = ('Vinayak',55,3.143278,'False')
print(t1[2],t1[3])
t1[2] == 54
print(t1[2])

dict = {
    'a':1,
    'b':2,
    'c':3
}
print(dict['a'])

mixed_list = [12,'abcd',90.34,5j,True,[1,'a'],(1,'f'),{'a':1,'b':2,'c':3}]
for i in mixed_list:
  print('{} is of datatype {}'.format(i,type(i)))